apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:6272f34e4580b610170d78c38cb2cd98741535b1728f78205f2c84700414f539
  name: quay.io/monishkumar/project-demo
  newName: quay.io/monishkumar/project-demo
